### ISSUE TITLE
Game update

### ISSUE THREAD

**Issue by C00kie-M0de** [emoisback/Helldivers-2-Internal-Hack-Dll-Proxy-PoC#27]
Was a small update pushed out just now and game stopped working with a message Gameguard detected cheat or hack.

**Comment by emoisback** [comment]
Yes im aware, maybe they detect dll proxy i dont know.. Let see when im home

**Comment by sigmaphi007** [comment]
I was able to start the game after they updarte .

**Comment by g020276j** [comment]
I've sorted a workaround until the patch is patched. @emoisback can you post this in your threat please?

1. Steam -> Library -> Helldivers 2 -> Right Click -> Manage -> Browse Local Files
2. Delete the 'tools' and 'bin' folders
3. In your own web browser visit `steam://nav/console`, click open with Steam
4. In the console, type "download_depot 553850 553851 1056784875343222032"
5. Navigate to the location the files were downloaded to, copy the 'bin' and 'tools' folders to the game directory
6. Copy hack DLL into 'bin' folder
7. Profit!!!

**Comment by DatGuyMcCaully** [comment]
> I've sorted a workaround until the patch is patched. @emoisback can you post this in your thread please?
> 
> 1. Steam -> Library -> Helldivers 2 -> Right Click -> Manage -> Browse Local Files
> 2. Delete the 'tools' and 'bin' folders
> 3. In your own web browser visit `steam://nav/console`, click open with Steam
> 4. In the console, type `download_depot 553850 553851 1056784875343222032`
> 5. Navigate to the location the files were downloaded to, copy the 'bin' and 'tools' folders to the game directory
> 6. Copy hack DLL into 'bin' folder
> 7. Profit!!!
> 
> EDIT: Nevermind, it's still detecting when you launch from hellpods, I'll look into it further

its working for me

![image](https://github.com/emoisback/Helldivers-2-Internal-Hack-Dll-Proxy-PoC/assets/96842650/114e2aeb-5ae9-43e4-8f76-b777cf22ac88)

**Comment by g020276j** [comment]
> > I've sorted a workaround until the patch is patched. @emoisback can you post this in your thread please?
> > 
> > 1. Steam -> Library -> Helldivers 2 -> Right Click -> Manage -> Browse Local Files
> > 2. Delete the 'tools' and 'bin' folders
> > 3. In your own web browser visit `steam://nav/console`, click open with Steam
> > 4. In the console, type `download_depot 553850 553851 1056784875343222032`
> > 5. Navigate to the location the files were downloaded to, copy the 'bin' and 'tools' folders to the game directory
> > 6. Copy hack DLL into 'bin' folder
> > 7. Profit!!!
> > 
> > EDIT: Nevermind, it's still detecting when you launch from hellpods, I'll look into it further
> 
> its working for me
> 
> ![image](https://private-user-images.githubusercontent.com/96842650/310896116-114e2aeb-5ae9-43e4-8f76-b777cf22ac88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTg2MTMsIm5iZiI6MTcwOTgxODMxMywicGF0aCI6Ii85Njg0MjY1MC8zMTA4OTYxMTYtMTE0ZTJhZWItNWFlOS00M2U0LThmNzYtYjc3N2NmMjJhYzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEzMzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYmZlZjljYTc2ZjU5ZjliM2QzNzhiNGY0ZGRkMWViZWVlMjQyNTdjYmFmYzNmMTYzYTk1YTIwMzhlYzRhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lg8DmBQVyaNK53Ch1jQTJMdACQ7oB-QNOj7sRL0gQqA)

It's letting you on your ship, and then in game?

**Comment by DatGuyMcCaully** [comment]
> > > I've sorted a workaround until the patch is patched. @emoisback can you post this in your thread please?
> > > 
> > > 1. Steam -> Library -> Helldivers 2 -> Right Click -> Manage -> Browse Local Files
> > > 2. Delete the 'tools' and 'bin' folders
> > > 3. In your own web browser visit `steam://nav/console`, click open with Steam
> > > 4. In the console, type `download_depot 553850 553851 1056784875343222032`
> > > 5. Navigate to the location the files were downloaded to, copy the 'bin' and 'tools' folders to the game directory
> > > 6. Copy hack DLL into 'bin' folder
> > > 7. Profit!!!
> > > 
> > > EDIT: Nevermind, it's still detecting when you launch from hellpods, I'll look into it further
> > 
> > 
> > its working for me
> > ![image](https://private-user-images.githubusercontent.com/96842650/310896116-114e2aeb-5ae9-43e4-8f76-b777cf22ac88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTg2MTMsIm5iZiI6MTcwOTgxODMxMywicGF0aCI6Ii85Njg0MjY1MC8zMTA4OTYxMTYtMTE0ZTJhZWItNWFlOS00M2U0LThmNzYtYjc3N2NmMjJhYzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEzMzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYmZlZjljYTc2ZjU5ZjliM2QzNzhiNGY0ZGRkMWViZWVlMjQyNTdjYmFmYzNmMTYzYTk1YTIwMzhlYzRhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lg8DmBQVyaNK53Ch1jQTJMdACQ7oB-QNOj7sRL0gQqA)
> 
> It's letting you on your ship, and then in game?

I lied, It just took about 5 mins for the detection.

**Comment by leogitsh** [comment]
> I've sorted a workaround until the patch is patched. @emoisback can you post this in your thread please?
> 
> 1. Steam -> Library -> Helldivers 2 -> Right Click -> Manage -> Browse Local Files
> 2. Delete the 'tools' and 'bin' folders
> 3. In your own web browser visit `steam://nav/console`, click open with Steam
> 4. In the console, type `download_depot 553850 553851 1056784875343222032`
> 5. Navigate to the location the files were downloaded to, copy the 'bin' and 'tools' folders to the game directory
> 6. Copy hack DLL into 'bin' folder
> 7. Profit!!!
> 
> EDIT: Nevermind, it's still detecting when you launch from hellpods, I'll look into it further


4. In the console, type `download_depot 553850 553851 1056784875343222032`

after this  I got this: Depot download failed : missing license for depots 553851

how to solve this problems

**Comment by g020276j** [comment]
> > I've sorted a workaround until the patch is patched. @emoisback can you post this in your thread please?
> > 
> > 1. Steam -> Library -> Helldivers 2 -> Right Click -> Manage -> Browse Local Files
> > 2. Delete the 'tools' and 'bin' folders
> > 3. In your own web browser visit `steam://nav/console`, click open with Steam
> > 4. In the console, type `download_depot 553850 553851 1056784875343222032`
> > 5. Navigate to the location the files were downloaded to, copy the 'bin' and 'tools' folders to the game directory
> > 6. Copy hack DLL into 'bin' folder
> > 7. Profit!!!
> > 
> > EDIT: Nevermind, it's still detecting when you launch from hellpods, I'll look into it further
> 
> 4. In the console, type `download_depot 553850 553851 1056784875343222032`
> 
> after this I got this: Depot download failed : missing license for depots 553851
> 
> how to solve this problems

You need to be logged into your Steam account which owns the game.

**Comment by Sinnisterly** [comment]
cfemens dll works great, no kicks, minus his damage and inf hp offsets needing updated, so its something with this one for sure. Even a fork of this with just the unlocks works.

**Comment by g020276j** [comment]
> > > > I've sorted a workaround until the patch is patched. @emoisback can you post this in your thread please?
> > > > 
> > > > 1. Steam -> Library -> Helldivers 2 -> Right Click -> Manage -> Browse Local Files
> > > > 2. Delete the 'tools' and 'bin' folders
> > > > 3. In your own web browser visit `steam://nav/console`, click open with Steam
> > > > 4. In the console, type `download_depot 553850 553851 1056784875343222032`
> > > > 5. Navigate to the location the files were downloaded to, copy the 'bin' and 'tools' folders to the game directory
> > > > 6. Copy hack DLL into 'bin' folder
> > > > 7. Profit!!!
> > > > 
> > > > EDIT: Nevermind, it's still detecting when you launch from hellpods, I'll look into it further
> > > 
> > > 
> > > its working for me
> > > ![image](https://private-user-images.githubusercontent.com/96842650/310896116-114e2aeb-5ae9-43e4-8f76-b777cf22ac88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTg2MTMsIm5iZiI6MTcwOTgxODMxMywicGF0aCI6Ii85Njg0MjY1MC8zMTA4OTYxMTYtMTE0ZTJhZWItNWFlOS00M2U0LThmNzYtYjc3N2NmMjJhYzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEzMzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYmZlZjljYTc2ZjU5ZjliM2QzNzhiNGY0ZGRkMWViZWVlMjQyNTdjYmFmYzNmMTYzYTk1YTIwMzhlYzRhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lg8DmBQVyaNK53Ch1jQTJMdACQ7oB-QNOj7sRL0gQqA)
> > 
> > 
> > It's letting you on your ship, and then in game?
> 
> Its working actually. I think its detected by the SetConsoleTitle function. I have a bunch of stuff edited in one and it works fine.
> 
> ![image](https://private-user-images.githubusercontent.com/96842650/310902118-8d8ffacc-e0a1-4f56-9ef7-8deea7a460af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTk4NDAsIm5iZiI6MTcwOTgxOTU0MCwicGF0aCI6Ii85Njg0MjY1MC8zMTA5MDIxMTgtOGQ4ZmZhY2MtZTBhMS00ZjU2LTllZjctOGRlZWE3YTQ2MGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEzNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZDBjYzk5NDE4MjI3NWIyZjM4MWUwZDY5NzZmOWU5N2M1ZjdhODBmNmNmMzM1Y2EzZmRlNDc5ZDExMGM2NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FN_n-WdrtluwprV2_jOU_KokcPfLMGo7NzLPRg2ASco)

Very interesting, so they literally patched this cheat only... bizarre behaviour

**Comment by DatGuyMcCaully** [comment]
> > > > > I've sorted a workaround until the patch is patched. @emoisback can you post this in your thread please?
> > > > > 
> > > > > 1. Steam -> Library -> Helldivers 2 -> Right Click -> Manage -> Browse Local Files
> > > > > 2. Delete the 'tools' and 'bin' folders
> > > > > 3. In your own web browser visit `steam://nav/console`, click open with Steam
> > > > > 4. In the console, type `download_depot 553850 553851 1056784875343222032`
> > > > > 5. Navigate to the location the files were downloaded to, copy the 'bin' and 'tools' folders to the game directory
> > > > > 6. Copy hack DLL into 'bin' folder
> > > > > 7. Profit!!!
> > > > > 
> > > > > EDIT: Nevermind, it's still detecting when you launch from hellpods, I'll look into it further
> > > > 
> > > > 
> > > > its working for me
> > > > ![image](https://private-user-images.githubusercontent.com/96842650/310896116-114e2aeb-5ae9-43e4-8f76-b777cf22ac88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTg2MTMsIm5iZiI6MTcwOTgxODMxMywicGF0aCI6Ii85Njg0MjY1MC8zMTA4OTYxMTYtMTE0ZTJhZWItNWFlOS00M2U0LThmNzYtYjc3N2NmMjJhYzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEzMzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYmZlZjljYTc2ZjU5ZjliM2QzNzhiNGY0ZGRkMWViZWVlMjQyNTdjYmFmYzNmMTYzYTk1YTIwMzhlYzRhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lg8DmBQVyaNK53Ch1jQTJMdACQ7oB-QNOj7sRL0gQqA)
> > > 
> > > 
> > > It's letting you on your ship, and then in game?
> > 
> > 
> > Its working actually. I think its detected by the SetConsoleTitle function. I have a bunch of stuff edited in one and it works fine.
> > ![image](https://private-user-images.githubusercontent.com/96842650/310902118-8d8ffacc-e0a1-4f56-9ef7-8deea7a460af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTk4NDAsIm5iZiI6MTcwOTgxOTU0MCwicGF0aCI6Ii85Njg0MjY1MC8zMTA5MDIxMTgtOGQ4ZmZhY2MtZTBhMS00ZjU2LTllZjctOGRlZWE3YTQ2MGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEzNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZDBjYzk5NDE4MjI3NWIyZjM4MWUwZDY5NzZmOWU5N2M1ZjdhODBmNmNmMzM1Y2EzZmRlNDc5ZDExMGM2NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FN_n-WdrtluwprV2_jOU_KokcPfLMGo7NzLPRg2ASco)
> 
> Very interesting, so they literally patched this cheat only... bizarre behaviour

I haven't tested with the new update, I followed your instructions first I'll verify my game and see if it works.

**Comment by g020276j** [comment]
> > > > > > I've sorted a workaround until the patch is patched. @emoisback can you post this in your thread please?
> > > > > > 
> > > > > > 1. Steam -> Library -> Helldivers 2 -> Right Click -> Manage -> Browse Local Files
> > > > > > 2. Delete the 'tools' and 'bin' folders
> > > > > > 3. In your own web browser visit `steam://nav/console`, click open with Steam
> > > > > > 4. In the console, type `download_depot 553850 553851 1056784875343222032`
> > > > > > 5. Navigate to the location the files were downloaded to, copy the 'bin' and 'tools' folders to the game directory
> > > > > > 6. Copy hack DLL into 'bin' folder
> > > > > > 7. Profit!!!
> > > > > > 
> > > > > > EDIT: Nevermind, it's still detecting when you launch from hellpods, I'll look into it further
> > > > > 
> > > > > 
> > > > > its working for me
> > > > > ![image](https://private-user-images.githubusercontent.com/96842650/310896116-114e2aeb-5ae9-43e4-8f76-b777cf22ac88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTg2MTMsIm5iZiI6MTcwOTgxODMxMywicGF0aCI6Ii85Njg0MjY1MC8zMTA4OTYxMTYtMTE0ZTJhZWItNWFlOS00M2U0LThmNzYtYjc3N2NmMjJhYzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEzMzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYmZlZjljYTc2ZjU5ZjliM2QzNzhiNGY0ZGRkMWViZWVlMjQyNTdjYmFmYzNmMTYzYTk1YTIwMzhlYzRhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lg8DmBQVyaNK53Ch1jQTJMdACQ7oB-QNOj7sRL0gQqA)
> > > > 
> > > > 
> > > > It's letting you on your ship, and then in game?
> > > 
> > > 
> > > Its working actually. I think its detected by the SetConsoleTitle function. I have a bunch of stuff edited in one and it works fine.
> > > ![image](https://private-user-images.githubusercontent.com/96842650/310902118-8d8ffacc-e0a1-4f56-9ef7-8deea7a460af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTk4NDAsIm5iZiI6MTcwOTgxOTU0MCwicGF0aCI6Ii85Njg0MjY1MC8zMTA5MDIxMTgtOGQ4ZmZhY2MtZTBhMS00ZjU2LTllZjctOGRlZWE3YTQ2MGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEzNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZDBjYzk5NDE4MjI3NWIyZjM4MWUwZDY5NzZmOWU5N2M1ZjdhODBmNmNmMzM1Y2EzZmRlNDc5ZDExMGM2NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FN_n-WdrtluwprV2_jOU_KokcPfLMGo7NzLPRg2ASco)
> > 
> > 
> > Very interesting, so they literally patched this cheat only... bizarre behaviour
> 
> I haven't tested with the new update, I followed your instructions first I'll verify my game and see if it works.

The instructions are in response to the game update, only....

**Comment by DatGuyMcCaully** [comment]
> > > > > > > I've sorted a workaround until the patch is patched. @emoisback can you post this in your thread please?
> > > > > > > 
> > > > > > > 1. Steam -> Library -> Helldivers 2 -> Right Click -> Manage -> Browse Local Files
> > > > > > > 2. Delete the 'tools' and 'bin' folders
> > > > > > > 3. In your own web browser visit `steam://nav/console`, click open with Steam
> > > > > > > 4. In the console, type `download_depot 553850 553851 1056784875343222032`
> > > > > > > 5. Navigate to the location the files were downloaded to, copy the 'bin' and 'tools' folders to the game directory
> > > > > > > 6. Copy hack DLL into 'bin' folder
> > > > > > > 7. Profit!!!
> > > > > > > 
> > > > > > > EDIT: Nevermind, it's still detecting when you launch from hellpods, I'll look into it further
> > > > > > 
> > > > > > 
> > > > > > its working for me
> > > > > > ![image](https://private-user-images.githubusercontent.com/96842650/310896116-114e2aeb-5ae9-43e4-8f76-b777cf22ac88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTg2MTMsIm5iZiI6MTcwOTgxODMxMywicGF0aCI6Ii85Njg0MjY1MC8zMTA4OTYxMTYtMTE0ZTJhZWItNWFlOS00M2U0LThmNzYtYjc3N2NmMjJhYzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEzMzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYmZlZjljYTc2ZjU5ZjliM2QzNzhiNGY0ZGRkMWViZWVlMjQyNTdjYmFmYzNmMTYzYTk1YTIwMzhlYzRhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lg8DmBQVyaNK53Ch1jQTJMdACQ7oB-QNOj7sRL0gQqA)
> > > > > 
> > > > > 
> > > > > It's letting you on your ship, and then in game?
> > > > 
> > > > 
> > > > Its working actually. I think its detected by the SetConsoleTitle function. I have a bunch of stuff edited in one and it works fine.
> > > > ![image](https://private-user-images.githubusercontent.com/96842650/310902118-8d8ffacc-e0a1-4f56-9ef7-8deea7a460af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTk4NDAsIm5iZiI6MTcwOTgxOTU0MCwicGF0aCI6Ii85Njg0MjY1MC8zMTA5MDIxMTgtOGQ4ZmZhY2MtZTBhMS00ZjU2LTllZjctOGRlZWE3YTQ2MGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEzNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZDBjYzk5NDE4MjI3NWIyZjM4MWUwZDY5NzZmOWU5N2M1ZjdhODBmNmNmMzM1Y2EzZmRlNDc5ZDExMGM2NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FN_n-WdrtluwprV2_jOU_KokcPfLMGo7NzLPRg2ASco)
> > > 
> > > 
> > > Very interesting, so they literally patched this cheat only... bizarre behaviour
> > 
> > 
> > I haven't tested with the new update, I followed your instructions first I'll verify my game and see if it works.
> 
> The instructions are in response to the game update, only....

yes my game was updated but I followed your instruction before testing anything.

**Comment by g020276j** [comment]
I've tried a rollback of 'bin', 'data', and 'tools' ,along with removing the "SetConsoleTitle" line, still crash

**Comment by DatGuyMcCaully** [comment]
> I've tried a rollback of 'bin', 'data', and 'tools' ,along with removing the "SetConsoleTitle" line, still crash

are you on the newest version in github? I havent updated the source since https://github.com/emoisback/Helldivers-2-Internal-Hack-Dll-Proxy-PoC/commit/7b95f7431a7295a8976b5f82b5c43f2e7d2244ec this edit. as I woke up an hour ago rofl.

**Comment by g020276j** [comment]
![image](https://github.com/emoisback/Helldivers-2-Internal-Hack-Dll-Proxy-PoC/assets/146968249/52e28a2e-3074-488d-abaa-6e2deee4c430)

So it appears the issue is coming from GameGuard itself, when you load the game, it downloads a new GameGuard update.
If you block GameGuard connections, the game refuses to start.

So in short, the game patch was misleading, GameGuard itself has had a patch, too

**Comment by DatGuyMcCaully** [comment]
> ![image](https://private-user-images.githubusercontent.com/146968249/310906392-52e28a2e-3074-488d-abaa-6e2deee4c430.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjEyOTAsIm5iZiI6MTcwOTgyMDk5MCwicGF0aCI6Ii8xNDY5NjgyNDkvMzEwOTA2MzkyLTUyZTI4YTJlLTMwNzQtNDg4ZC1hYmFhLTZlMmRlZWU0YzQzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxNDE2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmIzODJkM2VkMjk5ZDVkZjEyZWQ4MWYzZjcyNTMyOGU0ZGJjM2E3Y2QzMmU4MGQzZDIwOGQ1YjczNWZkN2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6LyqY-3SYxXdAw1sHWokrzdJA4uMJqOiZNaugUaqfb4)
> 
> So it appears the issue is coming from GameGuard itself, when you load the game, it downloads a new GameGuard update. If you block GameGuard connections, the game refuses to start.
> 
> So in short, the game patch was misleading, GameGuard itself has had a patch, too

I'm now on the newest cheat version, and newest game version with a bunch of stuff edited from the source code.

![image](https://github.com/emoisback/Helldivers-2-Internal-Hack-Dll-Proxy-PoC/assets/96842650/30fc27ff-5cea-4655-a226-34990720f4d1)

**Comment by g020276j** [comment]
> > ![image](https://private-user-images.githubusercontent.com/146968249/310906392-52e28a2e-3074-488d-abaa-6e2deee4c430.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjEyOTAsIm5iZiI6MTcwOTgyMDk5MCwicGF0aCI6Ii8xNDY5NjgyNDkvMzEwOTA2MzkyLTUyZTI4YTJlLTMwNzQtNDg4ZC1hYmFhLTZlMmRlZWU0YzQzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxNDE2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmIzODJkM2VkMjk5ZDVkZjEyZWQ4MWYzZjcyNTMyOGU0ZGJjM2E3Y2QzMmU4MGQzZDIwOGQ1YjczNWZkN2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6LyqY-3SYxXdAw1sHWokrzdJA4uMJqOiZNaugUaqfb4)
> > So it appears the issue is coming from GameGuard itself, when you load the game, it downloads a new GameGuard update. If you block GameGuard connections, the game refuses to start.
> > So in short, the game patch was misleading, GameGuard itself has had a patch, too
> 
> I'm now on the newest cheat version, and newest game version with a bunch of stuff edited from the source code.
> 
> ![image](https://private-user-images.githubusercontent.com/96842650/310910888-30fc27ff-5cea-4655-a226-34990720f4d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjE1MzUsIm5iZiI6MTcwOTgyMTIzNSwicGF0aCI6Ii85Njg0MjY1MC8zMTA5MTA4ODgtMzBmYzI3ZmYtNWNlYS00NjU1LWEyMjYtMzQ5OTA3MjBmNGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE0MjAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OWU4N2U4ZmZjOWJlMmE2NGExYzkwNmIyZWMzMTA3MzY4YjkyNzBjNDRlZmRjNzdjNzFiZjhmZmEyZDBjMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pod4stcc3QvqTH8EX2qAktWAs_PUdWINrzxoEy2b9S4)

I suspect, then, there's honey pots.
Try enabling the following cheats for me?
- Inf Stamina
- All Stratagems
- All Equipment
- All Armor

I believe stamina is now a honey pot

**Comment by DatGuyMcCaully** [comment]
> I suspect, then, there's honey pots. Try enabling the following cheats for me?
> 
> * Inf Stamina
> * All Stratagems
> * All Equipment
> * All Armor
> 
> I believe stamina is now a honey pot

Yep 

Inf Stamina
All Stratagems
All Equipment
All Armor

detected

**Comment by g020276j** [comment]
Sneaky buggers

**Comment by g020276j** [comment]
Detected if you select the bottom 3 without stamina?

**Comment by Sinnisterly** [comment]
https://prnt.sc/HlSe_n4xQEJs works fine for me now removing the consoletitle and other text at the top.

**Comment by DatGuyMcCaully** [comment]
> Detected if you select the bottom 3 without stamina?

yep just did last 3 detected.

**Comment by DatGuyMcCaully** [comment]
> > > https://prnt.sc/HlSe_n4xQEJs works fine for me now removing the consoletitle and other text at the top. Finished 2 missions so far.
> > 
> > 
> > All those cheats working fine?
> 
> yes, let me open my sln to see exactly what I removed. sec. ill edit this.

can you just sensitize the whole thing and upload it here?

**Comment by gir489returns** [comment]
The problem is FreeConsole doesn't work, probably the game is force-holding an instance to the console so we can't remove it. My personal build removes all that crap and just hard-sets the flags I want to true, and then skips to the do/while, works fine.

**Comment by Sinnisterly** [comment]
> > > > https://prnt.sc/HlSe_n4xQEJs works fine for me now removing the consoletitle and other text at the top. Finished 2 missions so far.
> > > 
> > > 
> > > All those cheats working fine?
> > 
> > 
> > yes, let me open my sln to see exactly what I removed. sec. ill edit this.
> 
> can you just sensitize the whole thing and upload the source here?

its as easy as removing/commenting out like 6 lines of code so no need tbh

**Comment by DatGuyMcCaully** [comment]
> > > > > https://prnt.sc/HlSe_n4xQEJs works fine for me now removing the consoletitle and other text at the top. Finished 2 missions so far.
> > > > 
> > > > 
> > > > All those cheats working fine?
> > > 
> > > 
> > > yes, let me open my sln to see exactly what I removed. sec. ill edit this.
> > 
> > 
> > can you just sensitize the whole thing and upload the source here?
> 
> its as easy as removing/commenting out like 6 lines of code so no need tbh

Yeah I saw the image. building now

**Comment by g020276j** [comment]
Yep I built it without all the bloat and console title, all working... what a bizarre cheat patch

**Comment by DatGuyMcCaully** [comment]
> Yep I built it without all the bloat and console title, all working... what a bizarre cheat patch

yeah just removed the console title and it works rofl wtf

**Comment by Sinnisterly** [comment]
its most likely, as this is the only public source for HD2 as far as I know, they are just scanning for the specific console title / text? Who knows... Cringe AC tactics for sure though.

**Comment by rorschach29** [comment]
> I've sorted a workaround until the patch is patched. @emoisback can you post this in your thread please?
> 
> 1. Steam -> Library -> Helldivers 2 -> Right Click -> Manage -> Browse Local Files
> 2. Delete the 'tools' and 'bin' folders
> 3. In your own web browser visit `steam://nav/console`, click open with Steam
> 4. In the console, type `download_depot 553850 553851 1056784875343222032`
> 5. Navigate to the location the files were downloaded to, copy the 'bin' and 'tools' folders to the game directory
> 6. Copy hack DLL into 'bin' folder
> 7. Profit!!!
> 
> EDIT: Nevermind, it's still detecting when you launch from hellpods, I'll look into it further

Do we still have to do this on top of editing out the title and stuff?

**Comment by g020276j** [comment]
Detection fixed: #30 
Thanks all who helped narrow down the cause!

**Comment by Sinnisterly** [comment]
> Detection fixed: #30 (pending merge) Thanks all who helped narrow down the cause!

I also put in a pull request 🤣 glad to see we were quick with it :)

**Comment by Sinnisterly** [comment]
for anyone just wanting the updated dll check my forked repo. Since emo can't have it on here because of UC's rules.

**Comment by bluemoon27112** [comment]
> for anyone just wanting the updated dll check my forked repo. Since emo can't have it on here because of UC's rules.

is your updated dll also need to avoid using some of the feature to prevent crash ?

**Comment by bluemoon27112** [comment]
> > > for anyone just wanting the updated dll check my forked repo. Since emo can't have it on here because of UC's rules.
> > 
> > 
> > is your updated dll also need to avoid using some of the feature to prevent crash ?
> 
> all the features should be working, I don't use inf health so I'm not sure if it's still bugged as per gir's issue post.

just tested , inf health seems to cause the fetal error

**Comment by Sinnisterly** [comment]
> > > > for anyone just wanting the updated dll check my forked repo. Since emo can't have it on here because of UC's rules.
> > > 
> > > 
> > > is your updated dll also need to avoid using some of the feature to prevent crash ?
> > 
> > 
> > all the features should be working, I don't use inf health so I'm not sure if it's still bugged as per gir's issue post.
> 
> just tested , inf health seems to cause the fetal error

the offset could have changed, I know the damage method that cfemen used also changed and is not working. I'm unable to fix it sorry!

**Comment by itztoken** [comment]
Trying the forked dll from Sinnisterly but it still gets detected for me. Surprisingly I'm sitting on the ship not even in mission and haven't even selected a an option from the menu. Went to check my second monitor and been hit with the hacking error whenever im idling

**Comment by Kahdeg-15520487** [comment]
from branch master, comment from line 116 "InitializeConsole();" to line 153 "} while (userInput != 13);" work

**Comment by Sinnisterly** [comment]
released a fixed DLL. It is currently working for me no issues, so test it and let me know if it works for everyone else please.

**Comment by TrypelZ** [comment]
WARNING ! With the fixed DLL as soon as you use unlock all and restart the game it kicks you for detected hack, even without the version.dll inside the game folder. Acoount is basically bricked now

**Comment by Sinnisterly** [comment]
> WARNING ! With the fixed DLL as soon as you use unlock all and restart the game it kicks you for detected hack, even without the version.dll inside the game folder. Acoount is basically bricked now

verify your game files and let me know if it fixes it.

**Comment by TrypelZ** [comment]
> > WARNING ! With the fixed DLL as soon as you use unlock all and restart the game it kicks you for detected hack, even without the version.dll inside the game folder. Acoount is basically bricked now
> 
> verify your game files and let me know if it fixes it.

Currently doing so, but even after pulling the version.dll out of the game folder and looking at my armory ( where everything i did not own is locked again ) it just boots me off for hack attempt

**Comment by LoneWolfLazarus** [comment]
Just to clarify to anyone whose wondering, I've been detected several times today, the game does NOT ban you, I think it must be done manually from the staff would be my best guess, I am gonna test if this works for now anyway.

**Comment by emoisback** [comment]
thanks guys for all your contribution.

ill think another way that more future proof.

**Comment by TrypelZ** [comment]
> > WARNING ! With the fixed DLL as soon as you use unlock all and restart the game it kicks you for detected hack, even without the version.dll inside the game folder. Acoount is basically bricked now
> 
> verify your game files and let me know if it fixes it.

Okay verifying files found 2 corrupt files, downloaded them and now everything works again as it should. Seems like something gets corrupt when using unlock all and restarting the game. Tried again now without unlock all and it works just fine even after restart.

**Comment by dexfreelancer** [comment]
> Just to clarify to anyone whose wondering, I've been detected several times today, the game does NOT ban you, I think it must be done manually from the staff would be my best guess, I am gonna test if this works for now anyway.
> 
> EDIT: Just forgot to mention the game just closes when you're detected.

there is no AC connectivity after launch so this is correct

**Comment by LoneWolfLazarus** [comment]
I am still getting detected what the hell have they done Arrowhead? I can't understand this for the life of me. Must be more frustrating for you guys if anything else, I didn't even get chance to activate anything...

**Comment by bluemoon27112** [comment]
with fixed dll , enable unlock all cheat and restart the game with or without dll , i DON'T get detected
weird

**Comment by LoneWolfLazarus** [comment]
I wish I was as lucky as you Moon! If you can use the .dll, it's detecting me constantly no matter what I do I just get detected, are you all using some kind of VPN or something? Just trying to figure things out is all. :)

**Comment by bluemoon27112** [comment]
> I wish I was as lucky as you Moon! If you can use the .dll, it's detecting me constantly no matter what I do I just get detected, are you all using some kind of VPN or something? Just trying to figure things out is all. :)

i don't use VPN as of now , i tried to wait 15 mins with or without dll , still don't get detected 
maybe you can try emoisback's latest dll ?

**Comment by Sinnisterly** [comment]
I've posted 2 release versions, one with xor strings same as master branch as well as skcrypter version. Try both, I am currently just using the skcrypter version and have been in game since my last post 25 minutes ago no detection.

**Comment by LoneWolfLazarus** [comment]
Thanks Sin, you too Moon! I just wanna be able to play the game the way I see fit y'know like rest of us. Should be a law against PvE GameGuards and stuff, bang out of order haha! I'll give it a go now thanks a lot dudes!

**Comment by Sinnisterly** [comment]
I agree ac on a pve game is cringe. I get their point, don't ruin the game for others, but gameguard wasn't the answer regardless. Let me know how it goes, if it works please reply!

**Comment by LoneWolfLazarus** [comment]
Wait it's detected? I just played a match and was fine. This is strange in the extreme!

**Comment by itztoken** [comment]
Been using XOR version from Sinnisterly and working great so far, no issues whatsoever.

**Comment by LoneWolfLazarus** [comment]
Same Token, I am hoping the GameGuard isn't adaptable to be fair, if it is, we're all in for some hard times regarding this game... As I am not sure how you can get around an ever adapting AC

**Comment by Sinnisterly** [comment]
glad they're working for you, that's all that matters really. I for some reason, cannot use either now 🤣 going back to cfemens dll till someone smarter than me figures it out.

**Comment by LoneWolfLazarus** [comment]
Well I've just tested again myself and well, I am now getting closed on for hack attempts, I could honestly strangle the CEO of GameGuard without hesitation lmao! 🤣

**Comment by Sinnisterly** [comment]
it is entirely the unlock feature so far, from testing for 15 minutes I didn't enable any of the unlock features this time and have not been closed out with the hack detected message, as well as everything else working. @emoisback maybe disable it on main temporarily?

**Comment by LoneWolfLazarus** [comment]
Don't you have to pay for Cfemens.dll? Does it absolutely work before I consider anything at all in the near future? I don't want to have to pay for something that may not be supported, fell for that with Cheat Happens recently, they just stuck the game on indefinite Hold like the muppets they are lol you should hear how they speak to folk on there, treat em like poop. Disgusting staff CE.

Anyway I cannot get in the game anymore now. My thinking is that they've made it adaptable the GameGuard.

**Comment by Sinnisterly** [comment]
> Don't you have to pay for Cfemens.dll? Does it absolutely work before I consider anything at all in the near future? I don't want to have to pay for something that may not be supported, fell for that with Cheat Happens recently, they just stuck the game on indefinite Hold like the muppets they are lol you should hear how they speak to folk on there, treat em like poop. Disgusting staff CE.
> 
> Anyway I cannot get in the game anymore now. My thinking is that they've made it adaptable the GameGuard.

verify your game, and some of cfemens features are not working currently as he hasn't updated it. Most work though. Also, Cheat happens claims to be singleplayer only, the fact they even had a trainer for HD2 is lucky. They're updating it afaik. I'm a lifetime plus member there haha.

**Comment by LoneWolfLazarus** [comment]
Ah okay, just from my experience I never comment on there because I don't want to end up getting bushwhacked and banned for sticking up for myself from their egocentric ways towards their fan/member base. I am Lifetime Member I think not sure about Plus though!

I'll verify it but usually takes a long time sometimes for me to verify. Which will make it a nightmare in the quintessential every time I want to boot up the game or switch which options I need. I will keep praying a perma solution will come soon. <3 Thank you to all of you here honestly, there needs to be a Starship Troopers meme inputted here for "I am doing my part" haha :P

**Comment by Sinnisterly** [comment]
yea my verify is buggy sometimes. Just steam things. I've pushed a release based off the latest master repo here but without the unlock features for anyone here.

**Comment by LoneWolfLazarus** [comment]
Yeah I refuse to use the unlock features as I was feeling pretty dubious about it, still not sure why I am verifying my game but I know you guys know a helluva lot more than me, shoulda stuck to them C++ classes instead of running off to smoke crack! 🤣 Just kidding. 👀

**Comment by LoneWolfLazarus** [comment]
If anyone wants to test as friends only I'd be much obliged to have someone join on me? I have all difficulties unlocked too so we should be ok to test thoroughly and profit in the mean time?

**Comment by Sinnisterly** [comment]
> Still no dice for me after verifying and stuff as you did Xal. I wish I had as much luck as most here! I think there's some human intervention going on either that or they've made it so that the AC adapts to it all.
> 
> EDIT: So I've resorted to trying the VS app, but I can't get the debugger to run what so ever, what am I doing wrong, keeps coming up with same bs-like error as before, no hack attempt detected just errors saying Unable to start program, bunch of addresses of where it's located pop up then pretty much anyway I get this below...
> 
> ![Stroll on](https://private-user-images.githubusercontent.com/162604083/310977526-737c80be-298d-4a90-8da5-6edd255d25f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzI0NzEsIm5iZiI6MTcwOTgzMjE3MSwicGF0aCI6Ii8xNjI2MDQwODMvMzEwOTc3NTI2LTczN2M4MGJlLTI5OGQtNGE5MC04ZGE1LTZlZGQyNTVkMjVmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxNzIyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGRhZjU0NDM1NjRmYTc4ODNjNTZmNDQwMTEwNWI1NmM4MTRmZGI1OWJkZTYyNWNjOTM2MTgwMzllZjhiN2RkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.weBrxLeEsXAnc-fkDfKnvrgjvkVCE-cuhTw8diWKKHk)

you don't run it via VS. you build it in there. tab at the top that says build>build solution. Will spit out the location of where it builds too in the bottom area "output"

**Comment by LoneWolfLazarus** [comment]
Ohhh okay, my bad, I'll give it a whirl now and see what happens.

**Comment by MoeyEvo** [comment]
> yea my verify is buggy sometimes. Just steam things. I've pushed a release based off the latest master repo here but without the unlock features for anyone here.

Can you please also update the source code as well for the latest dll u fixed thank you

**Comment by Sinnisterly** [comment]
> > yea my verify is buggy sometimes. Just steam things. I've pushed a release based off the latest master repo here but without the unlock features for anyone here.
> 
> Can you please also update the source code as well for the latest dll u fixed thank you

do you mean without the unlock features? sure let me make a seperate branch for it.

**Comment by Sinnisterly** [comment]
> Yeah this is absolutely absurd, won't be too surprised if they lose a lot of players because of this because there must be a looooot of people out there doing the same thing due to how absurdly difficult the game can be at times.
> 
> Also Sin, I get this when I build solution and I don't think anything is actually happening I am unsure.
> 
> Build started at 17:25... ========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ========== ========== Build completed at 17:25 and took 00.143 seconds ==========

I honestly am not sure why it isn't building. can you post a screenshot of the entire output section?

**Comment by LoneWolfLazarus** [comment]
I'll give this new update a go as VS goes over my head which is ironic as I am on a site which goes hand in hand with VS. But yeah anyway, I'll just wait 5 while you sort things out.

P.S: Absolutely Sin, I'll send you now in this post.

**Comment by MoeyEvo** [comment]
> yea my verify is buggy sometimes. Just steam things. I've pushed a release based off the latest master repo here but without the unlock features for anyone here.

can you please 

> > > yea my verify is buggy sometimes. Just steam things. I've pushed a release based off the latest master repo here but without the unlock features for anyone here.
> > 
> > 
> > Can you please also update the source code as well for the latest dll u fixed thank you
> 
> do you mean without the unlock features? sure let me make a seperate branch for it.

Yes, Thank you very much :)

**Comment by LoneWolfLazarus** [comment]
![Stroll on part 2 lol](https://github.com/emoisback/Helldivers-2-Internal-Hack-Dll-Proxy-PoC/assets/162604083/73393460-9b99-4bed-824f-e6ea9805d785)


Here you go Sin, thanks man!

**Comment by Sinnisterly** [comment]
> ![Stroll on part 2 lol](https://private-user-images.githubusercontent.com/162604083/310980935-73393460-9b99-4bed-824f-e6ea9805d785.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzMwNDgsIm5iZiI6MTcwOTgzMjc0OCwicGF0aCI6Ii8xNjI2MDQwODMvMzEwOTgwOTM1LTczMzkzNDYwLTliOTktNGJlZC04MjRmLWU2ZWE5ODA1ZDc4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxNzMyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTMzOTU2ZDA2NTU3OTVjNTlmNWJlYjExNTJiNjk1ZTE5NDA0MDNkMGIxYWIxMDdkMzU1MTIwN2M1ZThhYTEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ntD7tBAR9_6T8274O4WOHyxQ8PBvxR1Y06tw6FMAOT8)
> 
> Here you go Sin, thanks man!

check in your downloaded source for x64 folder with release folder inside. should have a version.dll there if so. If not let me know.

**Comment by Sinnisterly** [comment]
> > yea my verify is buggy sometimes. Just steam things. I've pushed a release based off the latest master repo here but without the unlock features for anyone here.
> 
> can you please
> 
> > > > yea my verify is buggy sometimes. Just steam things. I've pushed a release based off the latest master repo here but without the unlock features for anyone here.
> > > 
> > > 
> > > Can you please also update the source code as well for the latest dll u fixed thank you
> > 
> > 
> > do you mean without the unlock features? sure let me make a seperate branch for it.
> 
> Yes, Thank you very much :)

https://github.com/Sinnisterly/Helldivers-2-DLL-Releases/tree/xor-strings-nounlock here ya go :)

**Comment by LoneWolfLazarus** [comment]
Okay so Sin I do have a Version.dll but it's 66kb Yours is 33kb which is a bit confusing right now for me I guess.

**Comment by Sinnisterly** [comment]
> Okay so Sin I do have a Version.dll but it's 66kb Yours is 33kb which is a bit confusing right now for me I guess. It's been there the whole time yet Visual isn't picking it up, I don't understand that noise haha

mine is 33 because my vs is set up differently and I've removed the unlock code from mine. also, the version being there means you can drag+drop it in your bin folder, that is the completed build.

**Comment by LoneWolfLazarus** [comment]
Oh, so I can just drag and drop that one then and see if it runs?

**Comment by Sinnisterly** [comment]
> Oh, so I can just drag and drop that one then and see if it runs?

should do yea.

**Comment by LoneWolfLazarus** [comment]
Okay so it remembered my choices, interesting, I just activated soon as the game popped up tbh, then closed it, should still work, yes? :)

**Comment by LoneWolfLazarus** [comment]
Roger that, I'll deep strike now into a Helldiver difficulty Blitz mission and get back to you all in say... 30 - 40 mins? As I do tend to go OTT and finish EVERYTHING haha! :D

**Comment by LoneWolfLazarus** [comment]
Okay so Instant Railgun doesn't work, just has no effect when you shoot something like an Automaton. In fact, breaks the weapon completely, rest are all good. :)

**Comment by MoeyEvo** [comment]
@Sinnisterly you're a legend mate! helping out everyone and having the patience, I'm just getting into coding languages and your efforts to help everyone is greatly appreciated.

**Comment by rorschach29** [comment]
Yeah thanks man. I did c++ way back in college and just going through all of this, I have been able to get back into coding again.  Does your latest dll have the bile titan fix from emo too? Thanks again.

**Comment by TrypelZ** [comment]
So the latest DLL still gets GG error, removing the Version.dll and verifying files makes the game playable again but no matter what you do even with VS and C++ it crashes after a max of 5mins

**Comment by Sinnisterly** [comment]
> Yeah thanks man. I did c++ way back in college and just going through all of this, I have been able to get back into coding again. Does your latest dll have the bile titan fix from emo too? Thanks again.

yes it does, it seems emo is converting the code from having a console, to being a config file. I will probably stop updating my releases after he pushes it.

**Comment by LoneWolfLazarus** [comment]
I have found loading it with VS that you need to pick your options in VS, extract the DLL to the bin folder after building and THEN, launch the game, launch the hacks very quickly (similar to cheat happens), close the window, works. :) At least that it does for me. I hope it'll work for everyone else too.

**Comment by LoneWolfLazarus** [comment]
If anyone struggles with this way let me know and I'll apply a proper guide here or something, new to GitHub so I am unclear on how to fully use it yet. Gonna test my theories out soon with a friend who struggles to play without hax, she's getting on bless her but loves to play games with a friend or two so I'll letcha' all know..

**Comment by LoneWolfLazarus** [comment]
Deleted my last two posts because now it's back to "Hack Attempt" yada yada, someone giff me gun pls and point me in direction to Arrowhead lmao. Invalids the lot of em'. WHY OH WHY! Try so hard to make a PvE game so difficult to DO what *YOU* the player wants on? It's not like we're leaking their files we're just altering tidbits of them for others to have fun using what other people call 'hacks' etc. Anyway, long story short, I am gonna have to wait for another update because whatever it is they've done, they've made it nigh on impossible to be able to hack the game the way we see fit, it's a game after all, not a life changing product that saves lives, I don't get this behaviour from them what so ever, thought they were decent but they're actually putting me off the goddamn game doing this, sure I ain't the only one either...

**Comment by LoneWolfLazarus** [comment]
ALERT: We're not going to win this on GitHub, the dev is watching I am afraid.

"https://github.com/KingofEverythingg"

Has been watching the download pages across all of github related to Helldivers 2. Definitely not a player or one of us, we need to find a new place to upload.
